apiVersion: v1
kind: Service
metadata:
  name: nlb-tls-app
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "devpie.io"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    name: hello-kubernetes
  type: LoadBalancer
