apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: devpie-client-ingress-rules
  annotations:
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: devpie.io
      http:
        paths:
          - path: /
            backend:
              serviceName: hello-kubernetes-svc
              servicePort: 8080
